<header class="only-pc">
    <div class="Responsive">
        <div class="Menu">
            <div class="Menu-wrap">
                <a class="Menu-wrap-logo" href="#">
                    <img src="images/tgdd-logo.png" alt="logo">
                </a>
                <div class="Menu-wrap-search">
                    <div class="Menu-wrap-search-input">
                        <input type="text" placeholder="Bạn tìm gì...">
                    </div>
                    <div class="Menu-wrap-search-btn">
                        <i class="fas fa-search"></i>
                    </div>
                </div>
            </div>
            <div class="Menu-list">
                <a class="Menu-item" href="#">
                    <i class="fas fa-mobile-alt"></i>
                    <p>điện thoại</p>
                </a>
                <a class="Menu-item" href="#">
                    <i class="fas fa-tablet-alt"></i>
                    <p>tablet</p>
                </a>
                <a class="Menu-item" href="#">
                    <i class="fas fa-laptop-code"></i>
                    <p>laptop</p>
                </a>
                <a class="Menu-item" href="#">
                    <i class="fas fa-headphones-alt"></i>
                    <p>phụ kiện</p>
                </a>
                <a class="Menu-item" href="#">
                    <i class="far fa-clock"></i>
                    <p>đồng hồ</p>
                </a>
                <a class="Menu-item" href="#">
                    <i class="fas fa-mobile-alt"></i>
                    <p>điện thoại</p>
                </a>
                <a class="Menu-item" href="#">
                    <i class="far fa-newspaper"></i>
                    <p>tin tức</p>
                </a>
                <a class="Menu-item" href="#">
                    <i class="fab fa-whatsapp"></i>
                    <p>hỏi đáp</p>
                </a>
            </div>
            <div class="Menu-txt">
                <a class="Menu-txt-item" href="#">
                    <p>Sim số</p>
                    <p>Thẻ cào</p>
                </a>
                <a class="Menu-txt-item" href="#">
                    <p>Đóng tiền điện,</p>
                    <p>nước, trả góp</p>
                </a>
            </div>
        </div>
    </div>
</header>
<header class="only-sp">
    <div class="js-nav Nav">
        <div class="Nav-content">
            <a class="Nav__logo" href="#">
                <img src="images/tgdd-logo-sp.png" alt="logo">
            </a>
            <div class="Nav-search">
                <div class="Nav-search__input">
                    <input type="text" placeholder="Bạn tìm mua gì">
                </div>
                <div class="Nav-search__btn">
                    <i class="fas fa-search"></i>
                </div>
            </div>
            <div class="Nav-hamburger">
                <div class="js-navHamburger Nav-hamburger-content">
                    <span class="Nav-hamburger-content__ico"></span>
                    <span class="Nav-hamburger-content__ico"></span>
                    <span class="Nav-hamburger-content__ico"></span>
                </div>
            </div>
        </div>
        <div class="Nav-menu">
            <div class="Nav-menu-content">
                <div class="Nav-menu-content-list">
                    <a class="Nav-menu-content-item" href="#">
                        <h3>Điện thoại</h3>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h3>Tablet</h3>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h3>Laptop</h3>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h3>Phụ kiện</h3>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h4>Đồng hồ</h4>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h4>Mắt kính<br>thời trang</h4>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h4>Máy cũ<br>giá rẻ</h4>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h4>Sim số<br>thẻ cào</h4>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h4>Trả góp<br>Điện nước</h4>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h4>Tin tức<br>công nghệ</h4>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h4>Hỏi đáp</h4>
                    </a>
                    <a class="Nav-menu-content-item" href="#">
                        <h4>1.990<br>siêu thị</h4>
                    </a>
                </div>
                <div class="Nav-menu-content-phone">
                    <p>Gọi mua hàng: </p>
                    <a href="#">
                        <i class="fas fa-phone-square-alt"></i>
                        1800.1060
                    </a>
                    <span>(7:30 - 22:00)</span>
                </div>
            </div>
        </div>
    </div>
</header>